export const listDefault = [
  '⛺ Tent',
  '🛌 Sleeping Bag',
  '➖ Insulating Mat',
  '🔨 Hammer',
  '🔦 Solar light',
  '🚿 Solar shower',
  '🪝 Hook',
  '🪣 Water container',
  '🔶 Travel Towel',
  '🧻 Toilet Roll',
  '🐜 Repellent',
  '🥾 Wellie',
  '🧦 Wellie Socks',
  '🌧️ Poncho',
  '🎒 Waterproof Bag',
  '🔌 3 USB Socket',
  '✨ Bio Glitter',
  '🎟️ Festival Ticket',
  '💵 Cash',
  '🍴 Cutlery',
  '🍱 Bento box',
  '🥤 Straw',
  '🧽 Sponge',
  '🧼 Cloth',
  '🍵 Mug',
  '😷 Facemask',
  '🧂 Seasonings',
];

export const listSummer = [
  '🧴 Sun Protector',
  '🏖️ Beach Towel',
  '👙 Swimwear',
  '🕶️ Sun Glasses',
  '🩴 Flipflops',
  '🧢 Hat',
];
