export const listsAsObj = {
  listToiletries: [
    '🧴 Hand sanitiser',
    '🌸 Deodorant',
    '🦷 Toothpaste',
    '🪥 Toothbrush',
    '🧵 Floss',
    '🧼 Body soap',
    '🌝 Facial soap',
    '🌞 Facial SPF',
    '💋 Lip balm SPF',
    '💦 Moisturizer',
    '💆‍♀️ Shampoo',
    '🪮 Hair comb',
    '⭕ Hair tie',
    '💊 Vitamins / Pills',
    '🩹 Bandage',
    '🪒 Razor',
    '💅 Nail File / Clipper',
    '🩸 Period Cup / Pants',
    '🔘 Condoms',
  ],
  listZeroWaste: [
    '🍴 Cutlery',
    '🍱 Lunch box',
    '🥤 Straw',
    '🍵 Thermal cup',
    '🧽 Sponge',
    '🧼 Dish soap',
    '🔶 Cloth',
    '🍵 Mug',
    '😷 Face mask',
    '🧂 Seasonings',
  ],
  listFood: [
    '🍌 Fruits',
    '🍫 Protein bar',
    '🍿 Savouries',
    '🍩 Sweets',
    '🥐 Breakfast',
    '🥪 Sandwich',
  ],
  listTech: [
    '📱 Phone + charger',
    '🔋 Power bank + USB',
    '💻 Laptop + charger',
    '🎧 Earphones',
    '🔊 Speaker + charger',
    '🔌 Plug Adapter',
    '🕒 Watch + charger',
    '📷 Camera + charger',
    '🔥 Sex toys + charger',
    '🎮 Games + charger',
    '💨 Vape + charger',
  ],
  listEssentials: [
    '🪪 ID',
    '🛂 Passport',
    '💳 Cards',
    '💵 Cash',
    '🔑 Keys',
    '👓 Glasses / Lens',
    '😎 Sunglasses',
    '🥽 Eye mask',
    '👂 Earplugs',
    '🍶 Water bottle',
    '🧥 Raincoat',
    '🌂 Umbrella',
    '👝 Fanny pack',
    '✏️ Pencil',
    '📓 Notebook',
    '🔒 Padlock',
    '👟 Sneaker',
    '🥾 Boots',
    '🚊 Train tickets',
    '🚢 Boat tickets',
    '✈️ Airplane tickets',
    '🚍 Bus tickets',
  ],
  listLeaving: [
    '🪴 Water plants',
    '🗑️ Take out trash',
    '🪟 Close windows',
    '🧊 Get chilled food',
    '🔥 Turn off heating',
    '💡 Turn off lights',
    '📝 Review checklist',
    '🚪 Lock door',
  ],
  listClothes: [
    '👖 Trousers',
    '🩳 Shorts / Skirt',
    '👗 Dress',
    '👔 Shirts',
    '👚 Tops',
    '🧥 Coat / Jacket',
    '🩲 Underwear',
    '🧦 Socks',
    '🎽 Sportswear',
    '🕺 Party outfit',
    '😴 Pyjamas',
  ],
  listSummer: [
    '🧴 Sun lotion',
    '🏖️ Beach towel',
    '👙 Swimwear',
    '🩳 Bathing shorts',
    '🩴 Flip-flops',
    '🧢 Hat',
  ],
  listWinter: [
    '🧤 Gloves',
    '🧣 Scarf',
    '⛄ Beanie',
    '🧦 Winter socks',
    '🧶 Sweater',
    '🧥 Winter coat',
  ],
  listCamping: [
    '⛺ Tent',
    '🛌 Sleeping bag',
    '➖ Insulating mat',
    '🔦 Torch',
    '💡 Solar light',
    '🚿 Solar shower',
    '🔨 Mallet',
    '🔗 Carabiner',
    '🧻 Toilet roll',
    '🔶 Travel towel',
    '🪣 Water container',
    '⛑️ First Aid Kit',
    '🐜 Repellent',
    '🥾 Wellies',
    '🧦 Wellie socks',
    '🌧️ Poncho',
    '🎒 Waterproof bag',
    '✨ Eco-friendly glitter',
    '🎟️ Festival ticket',
  ],
  listAdditionals: [],
};
