type listEmojiType = {
  [key: string]: string;
};

export const listEmojis: listEmojiType = {
  listReusables: '💚',
  listSnacks: '🍎',
  listDevices: '⚡',
  listEssentials: '🎒',
  listClothes: '👕',
  listLeaving: '🚪',
  listSummer: '☀️',
  listWinter: '❄️',
  listToiletries: '🛁',
  listCamping: '🏕️',
  listAdditionals: '📝',
  'Hand sanitiser': "🧴",
  'Deodorant': "🌸",
  'Toothpaste': "🦷",
  'Toothbrush': "🪥",
  'Floss': "🧵",
  'Body soap': "🧼",
  'Facial soap': "🌝",
  'Facial SPF': "🌞",
  'Lip balm SPF': "👄",
  'Moisturizer': "💦",
  'Shampoo': "💆‍♀️",
  'Hair comb': "🔱",
  'Hair tie': "⭕",
  'Vitamins / Pills': "💊",
  'Bandage': "🩹",
  'Razor': "🪒",
  'Nail File / Clipper': "✂️",
  'Period Cup / Pants': "🩸",
  'Condoms': "🔘",
  'Water bottle': "🍶",
  'Cutlery': "🍴",
  'Lunch box': "🍱",
  'Straw': "🥤",
  'Thermal cup': "🍵",
  'Napkin': "🔶",
  'Face mask': "😷",
  'Fruits': "🍌",
  'Protein bar': "🍫",
  'Savouries': "🍿",
  'Sweets': "🍩",
  'Breakfast': "🥐",
  'Sandwich': "🥪",
  'Phone + charger': "📱",
  'Power bank + USB': "🔋",
  'Laptop + charger': "💻",
  'Earphones': "🎧",
  'Speaker + charger': "🔊",
  'Plug Adapter': "🔌",
  'Watch + charger': "🕒",
  'Camera + charger': "📷",
  'Sex toys + charger': "🔥",
  'Games + charger': "🎮",
  'E-reader + charger': "📙",
  'Vape + charger': "💨",
  'ID': "🪪",
  'Passport': "🛂",
  'Cards': "💳",
  'Cash': "💵",
  'Keys': "🔑",
  'Glasses / Lens': "👓",
  'Sunglasses': "😎",
  'Eye mask': "🥽",
  'Earplugs': "👂",
  'Raincoat': "🧥",
  'Umbrella': "🌂",
  'Fanny pack': "👝",
  'Pencil': "✏️",
  'Notebook': "📓",
  'Padlock': "🔒",
  'Sneaker': "👟",
  'Boots': "🥾",
  'Train tickets': "🚊",
  'Boat tickets': "🚢",
  'Airplane tickets': "✈️",
  'Bus tickets': "🚍",
  'Water plants': "🪴",
  'Take out trash': "🗑️",
  'Close windows': "🪟",
  'Get chilled snacks': "🧊",
  'Turn off heating': "🔥",
  'Turn off lights': "💡",
  'Review checklist': "📝",
  'Lock door': "🚪",
  'Trousers': "👖",
  'Shorts / Skirt': "🩳",
  'Dress': "👗",
  'Shirts': "👔",
  'Tops': "👚",
  'Coat / Jacket': "🧥",
  'Underwear': "🩲",
  'Socks': "🧦",
  'Sportswear': "🎽",
  'Party outfit': "🕺",
  'Pyjamas': "😴",
  'Sun lotion': "🧴",
  'Beach towel': "🏖️",
  'Swimwear': "👙",
  'Bathing shorts': "🩳",
  'Flip-flops': "🩴",
  'Hat': "🧢",
  'Gloves': "🧤",
  'Scarf': "🧣",
  'Beanie': "⛄",
  'Winter socks': "🧦",
  'Sweater': "🧶",
  'Winter coat': "🧥",
  'Tent': "⛺",
  'Sleeping bag': "🛌",
  'Insulating mat': "➖",
  'Torch': "🔦",
  'Solar light': "💡",
  'Solar shower': "🚿",
  'Mallet': "🔨",
  'Carabiner': "🔗",
  'Toilet roll': "🧻",
  'Travel towel': "🔶",
  'Water container': "🪣",
  'First Aid Kit': "⛑️",
  'Repellent': "🐜",
  'Wellies': "🥾",
  'Wellie socks': "🧦",
  'Poncho': "🌧️",
  'Waterproof bag': "🎒",
  'Eco-friendly glitter': "✨",
  'Festival ticket': "🎟️",
  'Sponge': "🧽",
  'Dish soap': "🧼",
  'MDMA': "🍭", 
  'Psychedelic': "🍄", 
  'Incense': "🪔",
  'Weed': "🌿",
  'Gift': "🎁"
};


