type listEmojiType = {
  [key: string]: string;
};

export const listEmojis: listEmojiType = {
  listReusables: '💚',
  listSnacks: '🍎',
  listDevices: '⚡',
  listEssentials: '🎒',
  listClothes: '👕',
  listLeaving: '🚪',
  listSummer: '☀️',
  listWinter: '❄️',
  listToiletries: '🛁',
  listCamping: '🏕️',
  listAdditionals: '📝',
  'hand sanitiser': "🧴",
  'deodorant': "🌸",
  'toothpaste': "🦷",
  'toothbrush': "🪥",
  'floss': "🧵",
  'body soap': "🧼",
  'facial soap': "🌝",
  'facial spf': "🌞",
  'lip balm spf': "👄",
  'moisturizer': "💦",
  'shampoo': "💆‍♀️",
  'hair comb': "🪮",
  'hair tie': "⭕",
  'vitamins / pills': "💊",
  'bandage': "🩹",
  'razor': "🪒",
  'nail file / clipper': "✂️",
  'period cup / pants': "🩸",
  'condoms': "🔘",
  'water bottle': "🍶",
  'tote bag': "🛍️", 
  'cutlery': "🍴",
  'lunch box': "🍱",
  'straw': "🥤",
  'thermal cup': "🍵",
  'napkin': "🔶",
  'face mask': "😷",
  'fruits': "🍌",
  'protein bar': "🍫",
  'savouries': "🍿",
  'sweets': "🍩",
  'breakfast': "🥐",
  'sandwich': "🥪",
  'phone + charger': "📱",
  'power bank + usb': "🔋",
  'laptop + charger': "💻",
  'earphones': "🎧",
  'speaker + charger': "🔊",
  'plug adapter': "🔌",
  'watch + charger': "⌚",
  'camera + charger': "📷",
  'sex toys + charger': "🔥",
  'games + charger': "🎮",
  'e-reader + charger': "📙",
  'vape + charger': "💨",
  'id': "🪪",
  'passport': "🛂",
  'cards': "💳",
  'cash': "💵",
  'keys': "🔑",
  'glasses / lens': "👓",
  'sunglasses': "😎",
  'eye mask': "🥽",
  'earplugs': "👂",
  'raincoat': "🧥",
  'umbrella': "☂️",
  'fanny pack': "👝",
  'pencil': "✏️",
  'notebook': "📓",
  'padlock': "🔒",
  'sneaker': "👟",
  'boots': "🥾",
  'train tickets': "🚊",
  'boat tickets': "🚢",
  'airplane tickets': "✈️",
  'bus tickets': "🚍",
  'water plants': "🪴",
  'take out trash': "🗑️",
  'close windows': "🪟",
  'get chilled snacks': "🧊",
  'turn off heating': "🔥",
  'turn off lights': "💡",
  'review checklist': "📝",
  'lock door': "🚪",
  'trousers': "👖",
  'shorts / skirt': "🩳",
  'dress': "👗",
  'shirts': "👔",
  'tops': "👚",
  'coat / jacket': "🧥",
  'underwear': "🩲",
  'socks': "🧦",
  'sportswear': "🎽",
  'party outfit': "🕺",
  'pyjamas': "😴",
  'sun lotion': "🧴",
  'beach towel': "🏖️",
  'swimwear': "👙",
  'bathing shorts': "🩳",
  'flip-flops': "🩴",
  'hat': "🧢",
  'gloves': "🧤",
  'scarf': "🧣",
  'beanie': "⛄",
  'winter socks': "🧦",
  'sweater': "🧶",
  'winter coat': "🧥",
  'tent': "⛺",
  'sleeping bag': "🛌",
  'insulating mat': "➖",
  'torch': "🔦",
  'solar light': "💡",
  'solar shower': "🚿",
  'mallet': "🔨",
  'carabiner': "🔗",
  'toilet roll': "🧻",
  'travel towel': "🔶",
  'water container': "🪣",
  'first aid kit': "⛑️",
  'repellent': "🐜",
  'wellies': "🥾",
  'wellie socks': "🧦",
  'poncho': "🌧️",
  'waterproof bag': "🎒",
  'eco-friendly glitter': "✨",
  'festival ticket': "🎟️",
  'sponge': "🧽",
  'dish soap': "🧼",
  'mdma': "🍭", 
  'psychedelic': "🍄", 
  'incense': "🪔",
  'weed': "🌿",
  'gift': "🎁",
  'concealer': "👁️",
  'poo-pourri': "💩",
  'hair styling': "➰",
  'dry shampoo': "🍚",
  'seasoning': "🧂",
  'earphone splitter': '♈',
  'open closet': '🌬️',
};


